#128 signup login frontend validation
gcivil-nyu-org/team-2-inperson pull request #153
Opened 2022-11-08 20:53 UTC by Pooja-Codes

- Added frontend validation on the signup and login page.
- Updated UI to show validation message
- Added package vuelidate
- Validation rules can be updated later according to team suggestions. The minor flow bug should be fixed with API integration.

2022-11-08 21:07 UTC, simaoalicechen commented on src/frontend/shortlist/src/components/layout/signup_login/Login.vue
> +import useVuelidate from "@vuelidate/core";
Really good way to do this.

2022-11-08 21:09 UTC, simaoalicechen commented on src/frontend/shortlist/src/components/layout/signup_login/Signup.vue
> +  let validNamePattern = new RegExp("^[a-zA-Z]+(?:[-'\\s][a-zA-Z]+)*$");
Good testing function.

2022-11-08 21:11 UTC, Pooja-Codes commented on src/frontend/shortlist/src/components/layout/signup_login/Login.vue
> +import useVuelidate from "@vuelidate/core";
Thank You!

2022-11-08 21:24 UTC, simaoalicechen requested changes

2022-11-08 21:24 UTC, simaoalicechen commented on src/frontend/shortlist/src/components/layout/signup_login/Signup.vue
>        <p class="instructions" id="small">Have an account already?</p>
I realize that you have LoginWithSSO in Login, but does not have SignupWithSSO. Maybe add them or delete both of them?

2022-11-08 21:35 UTC, Pooja-Codes commented on src/frontend/shortlist/src/components/layout/signup_login/Signup.vue
>        <p class="instructions" id="small">Have an account already?</p>
The user can not signup with google due to an ID upload requirement. However, they can log in with google if they are verified. Feel free to discuss about application flow doubts/suggestions later in the meeting.

2022-11-08 21:38 UTC, simaoalicechen commented on src/frontend/shortlist/src/components/layout/signup_login/Signup.vue
>        <p class="instructions" id="small">Have an account already?</p>
Nice.  One thing to communicate with the backend is that if we use the LoginWithSSO, when the user login with a Google account (an email account I assume), email is a required variable then.

2022-11-08 23:50 UTC, Pooja-Codes commented on src/frontend/shortlist/src/components/layout/signup_login/Signup.vue
>        <p class="instructions" id="small">Have an account already?</p>
Email is the required variable, you are right. Also, there is NO username according to the product owner-note for theAPI.

2022-11-09 01:32 UTC, waltage commented
LGTM; get alice's review ironed out and we're good

2022-11-09 01:33 UTC, waltage approved these changes

2022-11-09 01:54 UTC, simaoalicechen approved these changes

2022-11-09 02:11 UTC, yalexublue approved these changes
LGTM

2022-11-09 02:16 UTC, merged