added request-resend-email endpoint
gcivil-nyu-org/team-2-inperson pull request #164
Opened 2022-11-13 04:45 UTC by jainsvaibhav

2022-11-13 04:46 UTC, jainsvaibhav commented
please ignore the first three commits in this branch, bc the same commits are included into merge api and authentication app and endpoint pr. @waltage @adelaidemz @yalexublue

2022-11-13 20:36 UTC, waltage requested changes
Make changes to email link to be actual <a href='......>MESSAGE FOR LINK</a> etc. (both here and in the original email

2022-11-13 20:36 UTC, jainsvaibhav commented on src/backend/server/authentication/views.py
> +			    "email_subject": "Activate your account",
change the email to a href and click button

2022-11-14 03:41 UTC, jainsvaibhav commented
Merging it to develop based on the OH discussion

2022-11-14 03:41 UTC, merged