55 GitHub setup project source tree
gcivil-nyu-org/team-2-inperson pull request #56
Opened 2022-09-29 15:41 UTC by waltage

Contributing a high-level tree structure proposal as we begin the architecture discussions and the design docs;  

I'm also taking this opportunity to demonstrate some of the functionality we'll use over time -- 

1. Taking an issue and creating a separate "branch" for it (this case it's 55-github-setup....)
2. Making changes and commits in a local environment (with action phrases as the commit message, and as individually reversible changes)
3. Initiating a pull request (PR) for reviewers to double check (in this case I've selected the whole team)
4. Once **all reviewers** give a "Looks Good To Me" or (LGTM), then we can "merge" the PR into the corresponding main branch (in this case, it will go into "develop" while we wait for the rest of the branch details to come from Prof & TA)
5. Until we have all approval from reviewers, we need to make changes and collaborate on getting it to LGTM status, or to close it out 

Our team will make our own decisions about how our review process will work, but the above is an "average" flow that I've illustrated here in the meantime.

2022-09-30 13:17 UTC, yalexublue approved these changes
Looks good! Some folder name terms I don't really know what they refer to but I'm sure they have their meanings. I agree to merge to Develop

2022-09-30 19:42 UTC, waltage commented
> Looks good! Some folder name terms I don't really know what they refer to but I'm sure they have their meanings. I agree to merge to Develop

For practice, revoke your approval and go into the changes to find a folder you don't understand yet, and make a comment/question on it @yalexublue

2022-10-02 23:23 UTC, waltage commented on docs/README.md
> +5. Instructions for Postman (testing the API)
What is postman?

2022-10-02 23:24 UTC, jainsvaibhav commented on docs/README.md
> +4. Instructions for Travis (continuous integration)
test comment

2022-10-02 23:25 UTC, jainsvaibhav requested changes
please make change

2022-10-04 12:02 UTC, adelaidemz approved these changes

2022-10-04 14:06 UTC, jainsvaibhav approved these changes
LGTM

2022-10-04 17:09 UTC, merged